### PR TITLE
feat(platform): support the Gentoo distributions

### PR DESCRIPTION
**Pull request by baby-gnu**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

The support of Gentoo platform only requires the correct package name.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@baby-gnu Thanks for this PR.  We should enable these two lines as well:

https://github.com/saltstack-formulas/cert-formula/blob/8b810426b11aa1965b020aeb99d9ccc735c14b36/.gitlab-ci.yml#L151-L152

Since they need to be updated in the `ssf-formula` anyway, I'll run a quick test and then push them through if they work.  If they don't work, you'll hear from me soon enough!

**Comment by myii** [comment]
@baby-gnu Both instances are working:

* https://gitlab.com/myii/cert-formula/-/pipelines/292444112

I'll push through the commit directly using the `ssf-formula` soon.

**Comment by baby-gnu** [comment]
> @baby-gnu Both instances are working:
> 
>     * https://gitlab.com/myii/cert-formula/-/pipelines/292444112
> 
> 
> I'll push through the commit directly using the `ssf-formula` soon.

Yes, I tested it locally ;-)

**Comment by myii** [comment]
@baby-gnu [Done](https://github.com/myii/ssf-formula/pull/320), Gentoo enabled (8b810426b11aa1965b020aeb99d9ccc735c14b36).  Also took the opportunity to fix the `rubocop` violations and enable it in `pre-commit` (12030ab74a1bdf013db78960796a920f4487a104).  Tested before pushing:

* https://gitlab.com/myii/cert-formula/-/pipelines/292477675

**Comment by baby-gnu** [comment]
@myii thanks a lot.

**Pull request merged**
