### PR TITLE
fix(update): allow for empty pillar without state fail

### PR DESCRIPTION
**Pull request by seerickcode**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#44 

### Describe the changes you're proposing

Add a test.nop state so that the sls will always have something for onchanges to see even if there are no certs

### Pillar / config required to test the proposed changes

Just don't have any pillar data.

### Documentation checklist
Bug fix, not feature.  No documentation needed I feel.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by daks — APPROVED** [review]
Good catch. I agree with the fact that formulas should work by default even without pillar

**Comment by daks** [comment]
Before merging, CI errors must be fixed: can you change your commit message following https://github.com/saltstack-formulas/template-formula/blob/develop/docs/CONTRIBUTING.rst#linting-commit-messages-in-travis-ci?

Thanks

**Comment by seerickcode** [comment]
Hopefully that is an acceptable commit message now?  The bug is in update scope, but fix is in deploy.  After thought, perhaps fix(update,deploy) might have been better?

**Comment by Yoda-BZH** [comment]
Hello,

I'm experiencing this bug, and the proposed fix fixes the problem.

Thank you

**Comment by daks** [comment]
The code is OK for me too, but tests are failing and I'm not sure why because it work on my laptop(tm)

```
./bin/kitchen verify default-debian-10-master-py3

[...]

Profile Summary: 3 successful controls, 0 control failures, 0 controls skipped
Test Summary: 26 successful, 0 failures, 0 skipped
       Finished verifying <default-debian-10-master-py3> (0m1.87s).
-----> Test Kitchen is finished. (0m20.99s)
```

I don't have much time to dig into this problem so if anyone can look at it, it could be great.

**Comment by Yoda-BZH** [comment]
it all starts with :
```
[INFO    ] Executing state pkg.installed for [cert-package-install-pkg-installed]
[DEBUG   ] Could not LazyLoad pkg.resolve_capabilities: 'pkg.resolve_capabilities' is not available.
[INFO    ] Executing command dpkg-query in directory '/home/kitchen'
[DEBUG   ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[INFO    ] Executing command apt-cache in directory '/home/kitchen'
[INFO    ] Executing command apt-get in directory '/home/kitchen'
[INFO    ] Executing command dpkg in directory '/home/kitchen'
[INFO    ] Executing command systemd-run in directory '/home/kitchen'
[ERROR   ] Command 'systemd-run' failed with return code: 100
[ERROR   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
Package ssl-cert is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
[ERROR   ] stderr: Running scope as unit: run-rc8dc58695d3e42c88115b34e0850576c.scope
E: Package 'ssl-cert' has no installation candidate
[ERROR   ] retcode: 100
```

it probably works on your laptop because `ssl-cert` is already installed.

I don't see why it can't install this package.

**Comment by Yoda-BZH** [comment]
debian 10 test is now successful

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
Merged, thanks @seerickcode.

@daks @Yoda-BZH Appreciate your help in reviewing and getting this PR over the line.

**Pull request merged**
