### PR TITLE
Added Redhat Support

### PR DESCRIPTION
**Pull request by gwaters**
Added redhat support, and switched the map.jinja to look for OS Family rather than
just OS like other maps (redhat is splintered into lovely bits like centos, scientific linux, redhat, etc etc)

### CODE REVIEW

**Comment by aboe76** [comment]
@gwaters this will break with ubuntu and debian...have look at the other pull request? #3

**Comment by gwaters** [comment]
You are right, ubuntu is not the os family, its debian, we should change the map to reflect that. updating now, i have an ubuntu minion to try,

**Comment by gwaters** [comment]
Wait.. it already has both Debian and Ubuntu, and they are exactly the same. Other formulas like nagios, ntp, openssh rely on os_family. So I should remove the duplicate Ubuntu one, since it is in the Debian family.

**Comment by aboe76** [comment]
@daschatten Can you take a look ?

**Pull request merged**
