### PR TITLE
Allow to set certificate data from pillar

### LINKED ISSUE #9: Allow certificate from Pillar data
Currently the cert-formula requires certificates to reside in a salt:// location.

I have a use-case where I want to have both the certificate and key in Pillar data. I think thge formula should support this option as well.

### PR DESCRIPTION
**Pull request by kpostrup**
Closes #9

### CODE REVIEW

**Comment by tibold** [comment]
+1

I would need this feature too.

**Comment by 0xf10e** [comment]
Looks good to me.
What do you think, @aboe76 and @daschatten?

**Comment by aboe76** [comment]
@0xf10e I'm fine with this..should we wait on @daschatten

**Comment by 0xf10e** [comment]
@aboe76 let's give @daschatten another 24hrs to chime in ; )

**Comment by daks** [comment]
Hello,
any news about this PR?

**Comment by aboe76** [comment]
@daks sorry, that this slipped, merged.

**Comment by n-rodriguez** [comment]
@aboe76 thank you!

**Comment by daks** [comment]
thanks

**Pull request merged**
