### PR TITLE
Certificate removal, bug fixes and kitchen-salt tests!

### LINKED ISSUE #15: Add the ability to remove certs and keys
This formula doesn't offer a way to remove certificates and keys. I'll have a pull request to add in this functionality, however I was curious if there was any preference for doing this. I can do it one of two ways.

1. Create an "absent" state, put the contents of init.sls into a "present" state and have init.sls include the "absent" state, then the "present" state
2. Same as 1, except replacing init.sls with a "managed" state.

I would go with option 2, personally

### PR DESCRIPTION
**Pull request by ameneau**
Adds the ability to remove certificates by specifying "remove:True" in the pillar data.

Adds a helper module, cert_formula_helper that contains a method that can be used to find certificates matching certificate file contents (in the case you rename a certificate file but don't remember the old name, you can still find the certificate by its contents)

On debian family OSes where update-ca-certificates command needs to run, this now only runs the command one time at the end of the state. The update-ca-certificates command runs with the --fresh option due to prevent needing to manually clear out symlinks when removing certificates out of /usr/local/share/ca-certificates/ directory

Additionally, the default cert_dir has been set to /usr/local/share/ca-certificates for Debian family OSes since update-ca-certificates will function correctly as long as the certificate file has the .crt extension. Refs #12

Finally, includes some kitchen-salt tests that uses inspec to verify certificate/key installation and removal. It tests on Ubuntu 18.04 as well as CentOS 7, but not on Arch or SuSE. Additionally, I added a .travis.yml file, but we don't use travis CI internally, so I was not able to test that the .travis.yml file works properly. Please feel free to let me know if there are any changes I need to make to that.

Fixes #15 

@javierbertoli Thanks for your earlier feedback on this!

### CODE REVIEW

**Review by aboe76 — APPROVED** [review]
Looks good, nice work.

**Comment by javierbertoli** [comment]
Awesome, @ameneau! A little request, mind you add a line in [README](https://github.com/saltstack-formulas/cert-formula/blame/master/README.rst#L6) with a link to Travis tests status?, like

```yaml
.. image:: https://travis-ci.org/saltstack-formulas/cert-formula.svg?branch=master
```

@aboe76 I don't have permissions to enable travis on this repo, do you?

**Comment by aboe76** [comment]
@saltstack-formulas/core can anyone enable travis?

**Comment by whiteinge** [comment]
Enabled. Ping me if I missed anything.

**Comment by ameneau** [comment]
@javierbertoli I'll add that now!

Thanks @aboe76 and @whiteinge for getting travis enabled for this!

**Comment by javierbertoli** [comment]
thanks @ameneau! and @aboe76 & @whiteinge for your help :smile:

**Pull request merged**
